# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
# Travis is used to check supported versions of PHP only.
language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

  fast_finish: true

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - mkdir -p build/logs build/cov
  - php bin/phpunit -c phpunit.xml.dist

#after_success:
#  - travis_retry php bin/php-coveralls -v

notifications:
  email:
    - ronan.guilloux@gmail.com
